### PR TITLE
Zebra network architecture post

### PR DESCRIPTION
**Pull request by hdevalence**

### CODE REVIEW

**Comment by hdevalence** [comment]
Rebased the PR to change the date on the post to tomorrow.

**Comment by hdevalence** [comment]
This also changes the CSS in the following ways:

1. Changes blockquote text to italics in body font rather than roman header font, so that blockquotes are less visually jarring.
2. Changes code size to be the same as body size and adds a background to inline code as well as block code.

**Comment by sonyamann** [comment]
Merge at will :) or ACK and I'll merge tomorrow AM.

**Comment by acityinohio** [comment]
(oh whoops @sonyamann, missed your last comment, I will remove my review request!)

**Pull request merged**
