### PR TITLE
Cut down on the margins around the logo

### PR DESCRIPTION
**Pull request by RichardLitt**
Should be responsive.

### CODE REVIEW

**Comment by RichardLitt** [comment]
screen shot 2019-01-04 at 18 07 17

**Comment by sonyamann** [comment]
Thanks Rich. I hope you're not too horrified by the reduced whitespace :P We may end up tweaking this again in the future... (But seriously, I appreciate your flexibility.)

**Comment by sonyamann** [comment]
Any reason to keep the branch?

**Comment by RichardLitt** [comment]
Actually, it identified a good bug I needed to fix, so I'm happy. No worries. :) 

No. No reason to delete the branch, either.

**Pull request merged**
